### ISSUE TITLE
WikiText2 Dataset

### ISSUE THREAD

**Issue by xingyifei2016** [xjjxmu/QSLAW#3]
Hello authors, how do you get the wikitext2 dataset used for the sft script? I need it to reproduce the results.

**Comment by xjjxmu** [comment]
We used the [OmniQuant repository](https://github.com/OpenGVLab/OmniQuant) to obtain the quantization parameters for the Vicuna model. Since this process does not support multi-GPU parallelism, we haven't integrated it into our code yet. I suggest starting with the OmniQuant repository to get the quantization parameters for the LLM. Please note that OmniQuant does not default to using Vicuna as the quantization target, but since its structure is identical to LLaMA, you can directly include it in the LLaMA judgment logic. For data, you can see it in `OmniQuant/datautils.py`

**Comment by xingyifei2016** [comment]
Thank you, that answers my question.
