### ISSUE TITLE
How to Quantize alternative LLMs

### ISSUE THREAD

**Issue by xingyifei2016** [xjjxmu/QSLAW#7]
Hello authors, in an attempt to experiment on other settings such as LLaVA-v1.5 7b with vicuna-7b LLM, how do you quantize the 7b model? Could you provide the script to quantize this model?

**Comment by xjjxmu** [comment]
You can just change the model in scripts, there is no difference.

**Comment by xingyifei2016** [comment]
But the script requires a quantized LLM model, if I am not mistaken? This requires a quantized model before applying the multimodal learning? How do you quantize this LLM prior to running your training script?

**Comment by xingyifei2016** [comment]
Most importantly, I am asking how to obtain a corresponding omni_parameters.pth for a new model.

**Comment by xjjxmu** [comment]
> But the script requires a quantized LLM model, if I am not mistaken? This requires a quantized model before applying the multimodal learning? How do you quantize this LLM prior to running your training script?

To obtain the quantized model from QSLAW under other settings, you need to modify the model in the pretrain script and then apply this quantized model in the SFT stage.

**Comment by xjjxmu** [comment]
> Most importantly, I am asking how to obtain a corresponding omni_parameters.pth for a new model.

You can follow [OmniQuant](https://github.com/OpenGVLab/OmniQuant) to get omni_parameters.pth. Since this process of omniquant does not support multi-GPU parallelism, we haven't integrated it into our code yet.

Then, you can run the `modify.py` in our repo to ensure a correct parameter dictionary and set the `--resume` in the `pretrain.sh` to the quantized parameter path.

**Comment by xjjxmu** [comment]
If you have any other questions, feel free to open this issue!
